# version: '3.8'
# services:
#   backend:
#     build: ./backend
#     volumes:
#       - ./backend:/app
#     ports:
#       - "5000:5000"
#     environment:
#       - FLASK_ENV=development
#   frontend:
#     build: ./frontend
#     ports:
#       - "80:80"
#     depends_on:
#       - backend
# docker-compose.yml
version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
